# Initialization arrays using functions

In [1]:
import numpy as  np

In [2]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
type(a)

numpy.ndarray

In [4]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [8]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.full((3,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [11]:
np.full((2,3),50)

array([[50, 50, 50],
       [50, 50, 50]])

In [12]:
 np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

# Creating arrays using numerical ranges

In [14]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [15]:
np.linspace(10,30,5)

array([10., 15., 20., 25., 30.])

In [22]:
np.linspace(10,50,7,dtype='int',retstep=True)

(array([10, 16, 23, 30, 36, 43, 50]), np.float64(6.666666666666667))

In [17]:
np.linspace(100,200,3,dtype='int',retstep=True)

(array([100, 150, 200]), np.float64(50.0))

In [20]:
np.linspace(1,100,dtype='int')

array([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
        27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97, 100])

In [21]:
len(np.linspace(1,100,dtype='int'))

50

In [23]:
np.logspace(1,130,5,dtype='int')

/usr/local/lib/python3.11/dist-packages/numpy/_core/function_base.py:313: RuntimeWarning: invalid value encountered in cast
  return _nx.power(base, y).astype(dtype, copy=False)


array([                  10, -9223372036854775808, -9223372036854775808,
       -9223372036854775808, -9223372036854775808])

In [24]:
np.logspace(1,100,5,base=2,dtype='int')

/usr/local/lib/python3.11/dist-packages/numpy/_core/function_base.py:313: RuntimeWarning: invalid value encountered in cast
  return _nx.power(base, y).astype(dtype, copy=False)


array([                   2,             56431603,     1592262918131443,
       -9223372036854775808, -9223372036854775808])

In [25]:
np.arange(1,1000,43)

array([  1,  44,  87, 130, 173, 216, 259, 302, 345, 388, 431, 474, 517,
       560, 603, 646, 689, 732, 775, 818, 861, 904, 947, 990])

# Functions

In [26]:
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [27]:
a.ndim

1

In [28]:
b=np.copy(a)
b

array([1, 2, 3, 4, 5, 6])

In [29]:
a

array([1, 2, 3, 4, 5, 6])

In [30]:
b[2]=100

In [31]:
b

array([  1,   2, 100,   4,   5,   6])

In [32]:
a

array([1, 2, 3, 4, 5, 6])

In [33]:
c=a.view()
c

array([1, 2, 3, 4, 5, 6])

In [34]:
c[4]=200

In [35]:
c

array([  1,   2,   3,   4, 200,   6])

In [36]:
a

array([  1,   2,   3,   4, 200,   6])

In [37]:
a

array([  1,   2,   3,   4, 200,   6])

In [38]:
a.reshape(2,3)

array([[  1,   2,   3],
       [  4, 200,   6]])

In [39]:
a.reshape(3,2)

array([[  1,   2],
       [  3,   4],
       [200,   6]])

In [42]:
b=np.array([[2,1],[0,1]])
b

array([[2, 1],
       [0, 1]])

In [43]:
np.sort(b)

array([[1, 2],
       [0, 1]])

In [44]:
np.sort(b,axis=0)

array([[0, 1],
       [2, 1]])

In [51]:
np.sort(b,)[:,::-1]

array([[2, 1],
       [1, 0]])

In [52]:
a

array([  1,   2,   3,   4, 200,   6])

In [53]:
np.sort(a)

array([  1,   2,   3,   4,   6, 200])

In [54]:
np.sort(a)[::-1]

array([200,   6,   4,   3,   2,   1])

In [55]:
s='sunil'
s[::-1]

'linus'

In [57]:
s[::-1]

'linus'

In [58]:
a

array([  1,   2,   3,   4, 200,   6])

In [59]:
np.append(a,7)

array([  1,   2,   3,   4, 200,   6,   7])

In [60]:
np.delete(a,4)

array([1, 2, 3, 4, 6])

In [61]:
np.insert(a,2,100)

array([  1,   2, 100,   3,   4, 200,   6])

In [62]:
a

array([  1,   2,   3,   4, 200,   6])

In [63]:
a=np.arange(1,20,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [64]:
len(a)

10

In [66]:
a=a.reshape(2,5)
a

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [67]:
b=np.arange(21,40,2)
b

array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39])

In [68]:
b=b.reshape(2,5)
b

array([[21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39]])

In [69]:
a

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [70]:
np.concatenate((a,b))

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39]])

In [71]:
np.concatenate((a,b),axis=1)

array([[ 1,  3,  5,  7,  9, 21, 23, 25, 27, 29],
       [11, 13, 15, 17, 19, 31, 33, 35, 37, 39]])

In [72]:
np.hstack((a,b))

array([[ 1,  3,  5,  7,  9, 21, 23, 25, 27, 29],
       [11, 13, 15, 17, 19, 31, 33, 35, 37, 39]])

In [73]:
np.vstack((a,b))

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39]])

In [74]:
a

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [78]:
c=np.arange(20)

In [79]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [80]:
len(c)

20

In [81]:
x,y=np.split(c,2)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
y

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [84]:
len(x)

10

In [85]:
d,f,e,g,h=np.split(x,5)
d

array([0, 1])

In [86]:
e,f,g,h

(array([4, 5]), array([2, 3]), array([6, 7]), array([8, 9]))

In [87]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [88]:
np.where(c%2==0)

(array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18]),)

In [89]:
k=np.arange(60,81)
k

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76,
       77, 78, 79, 80])

In [90]:
np.where(k%2==0)

(array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20]),)

In [91]:
a

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [92]:
s=np.array([1,5,2,60,30,100])
s

array([  1,   5,   2,  60,  30, 100])

In [93]:
np.searchsorted(s,80)

np.int64(5)