In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
type(a)

numpy.ndarray

In [4]:
a.dtype

dtype('int64')

In [5]:
a=np.arange(1,20,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [7]:
b=np.linspace(1,20,2,retstep=True)
b

(array([ 1., 20.]), np.float64(19.0))

In [8]:
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [9]:
b=np.arange(21,40,2)

In [10]:
b

array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39])

In [11]:
len(a),len(b)

(10, 10)

In [12]:
np.add(a,b)

array([22, 26, 30, 34, 38, 42, 46, 50, 54, 58])

In [14]:
np.subtract(a,b)

array([-20, -20, -20, -20, -20, -20, -20, -20, -20, -20])

In [16]:
np.subtract(b,a)

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [17]:
np.multiply(a,b)

array([ 21,  69, 125, 189, 261, 341, 429, 525, 629, 741])

In [19]:
np.divide(b,a)

array([21.        ,  7.66666667,  5.        ,  3.85714286,  3.22222222,
        2.81818182,  2.53846154,  2.33333333,  2.17647059,  2.05263158])

In [20]:
np.exp(a)

array([2.71828183e+00, 2.00855369e+01, 1.48413159e+02, 1.09663316e+03,
       8.10308393e+03, 5.98741417e+04, 4.42413392e+05, 3.26901737e+06,
       2.41549528e+07, 1.78482301e+08])

In [21]:
np.sqrt(a)

array([1.        , 1.73205081, 2.23606798, 2.64575131, 3.        ,
       3.31662479, 3.60555128, 3.87298335, 4.12310563, 4.35889894])

In [22]:
np.array_equal(a,b)

False

In [23]:
a==b

array([False, False, False, False, False, False, False, False, False,
       False])

In [24]:
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [25]:
np.min(a)

np.int64(1)

In [26]:
np.max(a)

np.int64(19)

In [27]:
np.max(a)

np.int64(19)

In [28]:
np.sum(a)

np.int64(100)

In [29]:
np.mean(a)

np.float64(10.0)

In [30]:
np.median(a)

np.float64(10.0)

In [31]:
np.var(a)

np.float64(33.0)

In [32]:
np.std(a)

np.float64(5.744562646538029)

In [35]:
np.random.randint(100)

99

In [36]:
np.random.randint(100)

1

In [37]:
np.random.randint(100)

30

In [38]:
np.random.randint(1000,size=(2,3))

array([[178, 631,   1],
       [815, 202, 371]])

In [42]:
np.random.randint(1,1000,(4,5))

array([[ 49, 646, 336, 957, 663],
       [393, 439, 316, 619, 442],
       [443, 806,  78, 562, 658],
       [582, 668, 563, 799, 255]])

In [45]:
np.random.randint(100,500,(4,5))

array([[475, 439, 268, 396, 270],
       [423, 159, 210, 190, 488],
       [336, 122, 213, 151, 298],
       [425, 227, 147, 292, 319]])

In [46]:
np.random.rand(2,4)

array([[0.75295713, 0.53128206, 0.43846833, 0.24495498],
       [0.13743274, 0.24690175, 0.92857677, 0.32035074]])

In [47]:
np.random.rand(4,5)

array([[0.11991564, 0.03489096, 0.30864962, 0.41374179, 0.39778332],
       [0.03462865, 0.06167701, 0.62552138, 0.79875673, 0.81129731],
       [0.06838821, 0.0914342 , 0.31980727, 0.1753198 , 0.68893938],
       [0.92817342, 0.05518441, 0.55851326, 0.34805898, 0.43024337]])

In [48]:
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [49]:
np.random.choice(a)

np.int64(17)

In [50]:
np.random.choice(a)

np.int64(15)

In [51]:
np.random.choice(a)

np.int64(1)

In [53]:
import random
random.choices(a,k=2)

[np.int64(13), np.int64(19)]

In [54]:
random.choices(a,k=3)

[np.int64(9), np.int64(15), np.int64(9)]

In [56]:
random.choices(a,k=2)

[np.int64(7), np.int64(5)]

In [57]:
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [58]:
np.random.shuffle(a)

In [59]:
a

array([ 7, 17, 19,  5,  1,  3, 15,  9, 11, 13])

In [60]:
c=np.random.randint(1,100,(2,3))
c

array([[60, 86, 38],
       [ 8, 17,  9]])

In [61]:
np.random.shuffle(c)

In [62]:
c

array([[ 8, 17,  9],
       [60, 86, 38]])

In [64]:
np.random.shuffle(c)

In [65]:
c

array([[60, 86, 38],
       [ 8, 17,  9]])

In [66]:
np.random.shuffle(c)

In [67]:
c

array([[ 8, 17,  9],
       [60, 86, 38]])

In [68]:
d=np.random.randint(1,100,(4,5))
d

array([[82, 62, 25,  8, 38],
       [11,  5, 37, 28, 45],
       [11, 40, 33,  8, 37],
       [35, 61, 18, 89, 96]])

In [69]:
np.random.shuffle(d)

In [70]:
d

array([[82, 62, 25,  8, 38],
       [35, 61, 18, 89, 96],
       [11,  5, 37, 28, 45],
       [11, 40, 33,  8, 37]])

In [72]:
np.random.shuffle(d)

In [73]:
d

array([[11,  5, 37, 28, 45],
       [35, 61, 18, 89, 96],
       [82, 62, 25,  8, 38],
       [11, 40, 33,  8, 37]])

In [77]:
np.random.uniform(1,5,(2,3))

array([[1.98119658, 4.04526195, 4.84182542],
       [2.38281476, 4.33000327, 2.59155485]])

In [76]:
s={1,2,3,4,5,2,3,5}
s

{1, 2, 3, 4, 5}

In [78]:
np.random.rand(2,3)    # ---->  o to 1

array([[0.69731139, 0.03158082, 0.03877377],
       [0.50101545, 0.27675349, 0.7655442 ]])

In [79]:
np.random.uniform(1,100,(4,5))

array([[68.77428576, 47.41591765, 27.9960887 ,  7.93581671, 47.18299719],
       [50.86147826, 63.75850243, 57.29176291, 23.43270242, 70.9252943 ],
       [86.99256386, 30.0220068 , 44.34558408,  4.92100439, 92.26753897],
       [89.41992485, 75.64726183, 47.70428057, 62.10555605, 33.95949768]])

In [80]:
np.unique(a)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [81]:
u=np.array([1,2,3,1,2,4,5,7,7,4])
u

array([1, 2, 3, 1, 2, 4, 5, 7, 7, 4])

In [82]:
np.unique(u)

array([1, 2, 3, 4, 5, 7])

In [83]:
a

array([19, 17,  1, 15,  5, 13,  9, 11,  7,  3])

In [84]:
np.log(a)

array([2.94443898, 2.83321334, 0.        , 2.7080502 , 1.60943791,
       2.56494936, 2.19722458, 2.39789527, 1.94591015, 1.09861229])

In [85]:
np.sin(a)

array([ 0.14987721, -0.96139749,  0.84147098,  0.65028784, -0.95892427,
        0.42016704,  0.41211849, -0.99999021,  0.6569866 ,  0.14112001])

In [86]:
np.cos(a)

array([ 0.98870462, -0.27516334,  0.54030231, -0.75968791,  0.28366219,
        0.90744678, -0.91113026,  0.0044257 ,  0.75390225, -0.9899925 ])

In [87]:
np.min(a)

np.int64(1)

In [88]:
np.argmin(a)

np.int64(2)

In [89]:
a

array([19, 17,  1, 15,  5, 13,  9, 11,  7,  3])

In [90]:
np.max(a)

np.int64(19)

In [91]:
np.argmax(a)

np.int64(0)

In [92]:
np.argmin(a)

np.int64(2)

In [94]:
np.radians(a)

array([0.33161256, 0.29670597, 0.01745329, 0.26179939, 0.08726646,
       0.2268928 , 0.15707963, 0.19198622, 0.12217305, 0.05235988])

In [96]:
d=np.degrees(a)
d

array([1088.61981075,  974.02825172,   57.29577951,  859.4366927 ,
        286.47889757,  744.84513367,  515.66201562,  630.25357464,
        401.07045659,  171.88733854])

In [98]:
np.deg2rad(d)

array([19., 17.,  1., 15.,  5., 13.,  9., 11.,  7.,  3.])

In [99]:
a

array([19, 17,  1, 15,  5, 13,  9, 11,  7,  3])

In [102]:
b=a.astype('f')
b

array([19., 17.,  1., 15.,  5., 13.,  9., 11.,  7.,  3.], dtype=float32)

In [103]:
b

array([19., 17.,  1., 15.,  5., 13.,  9., 11.,  7.,  3.], dtype=float32)

In [104]:
b.astype('S1')

array([b'1', b'1', b'1', b'1', b'5', b'1', b'9', b'1', b'7', b'3'],
      dtype='|S1')

In [107]:
c=b'data science'
q=np.frombuffer(c,dtype='S1')
q

array([b'd', b'a', b't', b'a', b' ', b's', b'c', b'i', b'e', b'n', b'c',
       b'e'], dtype='|S1')

In [109]:
np.frombuffer(c,dtype='S1',offset=3,count=4)

array([b'a', b' ', b's', b'c'], dtype='|S1')

In [110]:
s=np.random.rand(2,3)
s

array([[0.21086533, 0.14723282, 0.12530065],
       [0.17993892, 0.71279762, 0.75561689]])

In [111]:
s.flatten()

array([0.21086533, 0.14723282, 0.12530065, 0.17993892, 0.71279762,
       0.75561689])

In [113]:
x=np.random.randint(1,100,(4,5))
x

array([[30, 31, 75, 32, 37],
       [31, 69, 63, 49, 72],
       [48, 21, 70, 88, 95],
       [88, 29, 76, 89, 59]])

In [118]:
x.ndim

2

In [116]:
d=x.flatten()
d

array([30, 31, 75, 32, 37, 31, 69, 63, 49, 72, 48, 21, 70, 88, 95, 88, 29,
       76, 89, 59])

In [117]:
d.ndim

1

In [119]:
x

array([[30, 31, 75, 32, 37],
       [31, 69, 63, 49, 72],
       [48, 21, 70, 88, 95],
       [88, 29, 76, 89, 59]])

In [120]:
x.reshape(-1)

array([30, 31, 75, 32, 37, 31, 69, 63, 49, 72, 48, 21, 70, 88, 95, 88, 29,
       76, 89, 59])

In [121]:
x=np.random.randint(1,100,(2,5))
x

array([[81, 28, 17, 64, 35],
       [ 1, 25, 51, 17, 98]])

In [122]:
x=x.reshape(-1)
x

array([81, 28, 17, 64, 35,  1, 25, 51, 17, 98])

In [123]:
len(x)

10

In [124]:
x[:8].reshape(2,4)

array([[81, 28, 17, 64],
       [35,  1, 25, 51]])

In [125]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [126]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])