In [1]:
pip install numpy

In [2]:
import numpy

In [3]:
numpy.__version__

'2.0.2'

# Creating Arrays

In [4]:
a=numpy.array(10)
a

array(10)

In [5]:
a.ndim

0

In [6]:
import numpy as np

In [7]:
a=np.array(10000)
a

array(10000)

In [8]:
a.ndim

0

In [9]:
b=np.array([1,2,3,4,5])
b

array([1, 2, 3, 4, 5])

In [10]:
b.ndim

1

In [11]:
c=np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
c.ndim

2

In [15]:
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [16]:
d.ndim

3

In [19]:
np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [20]:
e=np.array([5],ndmin=10)
e

array([[[[[[[[[[5]]]]]]]]]])

In [21]:
e.ndim

10

In [23]:
f=np.array([6],ndmin=20)
f

array([[[[[[[[[[[[[[[[[[[[6]]]]]]]]]]]]]]]]]]]])

In [24]:
f.ndim

20

In [25]:
t=b'Data Science'
g=np.frombuffer(t,dtype='S1')
g

array([b'D', b'a', b't', b'a', b' ', b'S', b'c', b'i', b'e', b'n', b'c',
       b'e'], dtype='|S1')

In [32]:
s='Data Science'
s.split()

['Data', 'Science']

In [33]:
np.frombuffer(t,dtype='S1',offset=3)

array([b'a', b' ', b'S', b'c', b'i', b'e', b'n', b'c', b'e'], dtype='|S1')

In [34]:
np.frombuffer(t,dtype='S1',offset=5)

array([b'S', b'c', b'i', b'e', b'n', b'c', b'e'], dtype='|S1')

In [35]:
np.frombuffer(t,dtype='S1',offset=3,count=5)

array([b'a', b' ', b'S', b'c', b'i'], dtype='|S1')

In [36]:
np.frombuffer(t,dtype='S1',offset=5,count=5)

array([b'S', b'c', b'i', b'e', b'n'], dtype='|S1')

In [39]:
np.fromiter([1,2,3],dtype='int')

array([1, 2, 3])

In [38]:
np.array([1,2,3])

array([1, 2, 3])

In [40]:
np.fromiter([1,2,3],dtype='float')

array([1., 2., 3.])

In [41]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [42]:
a.ndim

2

In [43]:
for i in a:
  print(i)

[1 2]
[3 4]


In [44]:
for i in a:
  for j in i:
    print(j)

1
2
3
4


In [45]:
for i in np.nditer(a):
  print(i)

1
2
3
4


In [49]:
for i in np.nditer(a,order='F'):
  print(i)

1
3
2
4


# Basic Checks


In [50]:
a

array([[1, 2],
       [3, 4]])

In [52]:
a.shape

(2, 2)

In [53]:
a.size

4

In [54]:
a.dtype

dtype('int64')

In [55]:
type(a)

numpy.ndarray

# Slicing

In [56]:
d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [57]:
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [58]:
d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
d[0][0]

array([1, 2, 3])

In [60]:
d[0][1][1]

np.int64(5)

In [61]:
d[0][0][2]

np.int64(3)

In [64]:
d[1][1][2]

np.int64(12)